### ISSUE TITLE
In guides, add anchor headings/hash links to the headings

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/victory-docs#198] opened 2016-11-08 22:27 UTC
Notes: 
- The guides use `<Ecology>` which uses `marked` 
- The /docs use `markdown-it-toc-and-anchor` 
- How can we use both? Pass a custom renderer to `<Ecology>`???????

**Comment by boygirl** [comment] 2017-05-01 16:14
duplicate of https://github.com/FormidableLabs/victory-docs/issues/286

**Closed by boygirl** 2017-05-01 16:14 UTC
